spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: h2
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        type: trace
  flyway:
    enabled: false